INSERT INTO TO_DO_ITEM_CATEGORY VALUES(1,'Groceries');
INSERT INTO TO_DO_ITEM_CATEGORY VALUES(2,'Office');
INSERT INTO TO_DO_ITEM_CATEGORY VALUES(3,'Travel');
INSERT INTO TO_DO_ITEM_CATEGORY VALUES(4,'Misc');